"""Add bidirectional sync and privacy mode support

Revision ID: 321dfae78f96
Revises: 003_remove_password_auth
Create Date: 2025-12-22 13:52:47.244789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321dfae78f96'
down_revision = '003_remove_password_auth'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_mappings', sa.Column('origin_calendar_id', sa.String(length=255), nullable=True))
    op.add_column('event_mappings', sa.Column('is_privacy_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sync_configs', sa.Column('sync_direction', sa.String(length=20), nullable=False, server_default=sa.text("'one_way'")))
    op.add_column('sync_configs', sa.Column('paired_config_id', sa.UUID(), nullable=True))
    op.add_column('sync_configs', sa.Column('privacy_mode_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('sync_configs', sa.Column('privacy_placeholder_text', sa.String(length=255), nullable=True, server_default=sa.text("'Personal appointment'")))
    op.create_foreign_key(None, 'sync_configs', 'sync_configs', ['paired_config_id'], ['id'], ondelete='SET NULL')
    op.add_column('sync_logs', sa.Column('sync_direction', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'sync_direction')
    op.drop_constraint(None, 'sync_configs', type_='foreignkey')
    op.drop_column('sync_configs', 'privacy_placeholder_text')
    op.drop_column('sync_configs', 'privacy_mode_enabled')
    op.drop_column('sync_configs', 'paired_config_id')
    op.drop_column('sync_configs', 'sync_direction')
    op.drop_column('event_mappings', 'is_privacy_mode')
    op.drop_column('event_mappings', 'origin_calendar_id')
    # ### end Alembic commands ###
