"""add auto-sync scheduling fields

Revision ID: 93a33b780cdd
Revises: 321dfae78f96
Create Date: 2026-01-04 18:54:50.767596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a33b780cdd'
down_revision = '321dfae78f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_configs', sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sync_configs', sa.Column('auto_sync_cron', sa.String(length=100), nullable=True))
    op.add_column('sync_configs', sa.Column('auto_sync_timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    # Create index for efficient filtering of auto-sync enabled configs
    op.create_index('ix_sync_configs_auto_sync_enabled', 'sync_configs', ['auto_sync_enabled'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sync_configs_auto_sync_enabled', table_name='sync_configs')
    op.drop_column('sync_configs', 'auto_sync_timezone')
    op.drop_column('sync_configs', 'auto_sync_cron')
    op.drop_column('sync_configs', 'auto_sync_enabled')
    # ### end Alembic commands ###
